### ISSUE TITLE
What happened to Solar/Citrus Lang?

### ISSUE THREAD

**Issue by sweezyio** [SimpleBinary/Simplebinary.github.io#4]
I apologize for contacting you via GitHub issue but I was unaware of any other way. 

What happened to Solar/Citrus Lang? I have a fork of the project when it was Solar but I can't find the original repo.

**Comment by d-siganos** [comment]
@KennethSweezy seems like they were not satisfied with the implementation

**Comment by d-siganos** [comment]
@SimpleBinary

**Comment by plastictortoise** [comment]
@BonfireScratch We realised that there was no practical use for the programming language.

**Comment by d-siganos** [comment]
@SimpleBinary what do you mean by that?
