### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by yessum** [SimpleBinary/Simplebinary.github.io#5]
No

**Comment by BonfireScratch** [comment]
You should only open issues when they are related to the repository

**Comment by BonfireScratch** [comment]
???

**Comment by yessum** [comment]
> Haha, lol. I'm going to laugh when you find this out. lolololololol. I'm very C++ legend, I use `sout`.

You don't have to bully me like that, BENJI.

**Comment by BonfireScratch** [comment]
What?
